// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-64vgm27DCGNT6lB85Kdsy8jBTuXmO2M',
    appId: '1:46106615155:web:da7aa945ad92b10fb97906',
    messagingSenderId: '46106615155',
    projectId: 'skillswap-40b74',
    authDomain: 'skillswap-40b74.firebaseapp.com',
    storageBucket: 'skillswap-40b74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8rpNl9Pht0bGBoyhJPnt8bid8SAA7ENg',
    appId: '1:46106615155:android:9ce8a93687b1a0cfb97906',
    messagingSenderId: '46106615155',
    projectId: 'skillswap-40b74',
    storageBucket: 'skillswap-40b74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiR6qfXBXf6N_QtUwKFlXaiUKMsBsSMKE',
    appId: '1:46106615155:ios:d11baf8e6de7cefdb97906',
    messagingSenderId: '46106615155',
    projectId: 'skillswap-40b74',
    storageBucket: 'skillswap-40b74.firebasestorage.app',
    iosBundleId: 'com.skillswap.skillswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiR6qfXBXf6N_QtUwKFlXaiUKMsBsSMKE',
    appId: '1:46106615155:ios:d11baf8e6de7cefdb97906',
    messagingSenderId: '46106615155',
    projectId: 'skillswap-40b74',
    storageBucket: 'skillswap-40b74.firebasestorage.app',
    iosBundleId: 'com.skillswap.skillswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-64vgm27DCGNT6lB85Kdsy8jBTuXmO2M',
    appId: '1:46106615155:web:d3df703f5339b866b97906',
    messagingSenderId: '46106615155',
    projectId: 'skillswap-40b74',
    authDomain: 'skillswap-40b74.firebaseapp.com',
    storageBucket: 'skillswap-40b74.firebasestorage.app',
  );
}
